spring:
  #集群版
  redis:
    cluster:
      nodes: 10.34.12.145:6390,10.34.50.197:6391,10.34.12.97:6392,10.34.12.145:6393,10.34.50.197:6394,10.34.12.97:6395
      max-redirects: 3
    password: zj000001
    timeout: 5000
    database: 0
    lettuce:
      pool:
        max-active: 300
        max-wait: 500
        max-idle: 10
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.34.12.145:3306/usp_auth?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: cloud.Zijin
    druid:
      initial-size: 1
      min-idle: 5
      max-active: 20
      max-wait: 10000
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000
      validation-query: "SELECT 1"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          enabled: true
          db-type: mariadb
          log-slow-sql: true
          slow-sql-millis: 10000

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 3000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1

feign:
  sentinel:
    enabled: true

logging:
  level:
    com.zjft.usp: debug
    com.alibaba.nacos.client.naming: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS