// 系统平台
export const SYS_RIGHT = {
  SYS_CLOUD: '1',
  CLOUD_MANAGE: '2', // 平台管理
  TENANT: '3', TENANT_ADD: '4', TENANT_MOD: '5', TENANT_DEL: '6', TENANT_VIEW: '7', // 租户管理
  RIGHT: '8', RIGHT_ADD: '9', RIGHT_MOD: '10', RIGHT_DEL: '11', RIGHT_MATCH: '12', RIGHT_CORP: '13', // 权限管理
  RIGHT_URL: '14', RIGHT_URL_ADD: '15', RIGHT_URL_MOD: '16', RIGHT_URL_DEL: '17', // 鉴权管理
  CORP_VERIFY: '18', CORP_VERIFY_APPLY: '46', CORP_VERIFY_AUDIT: '19', // 企业认证
  CORP_LIST: '20', CORP_ADMIN_ADD: '21', // 企业列表
  TOKEN: '22', // 凭证管理
  LOGIN_LOG: '425',// 登录日志
  OPERATION_LOG: '426',// 用户操作日志
  USER_INFO_MANAGE: '429',// 用户管理
  HIDDEN: '433',  // 设置人员显示/隐藏
  REDIS: '435', // Redis管理
  USER_RIGHT: '23', // 用户权限
  VERIFY_DETAILS: '436',  // 查看认证信息
  REGISTRY_EDIT: '437',  // 编辑企业注册信息
  VERIFY_EDIT: '438',  // 编辑认证信息
  REG_USER_EDIT: '444',  // 编辑注册人
  VERIFY: '439',  // 企业认证
};

// 账户系统
export const UAS_RIGHT = {
  SYS_UAS: '24', // 账户系统
  CORP_USER_MANAGE: '25', CORP_USER_ADD: '26', CORP_USER_MOD: '27', CORP_USER_DEL: '28',
  CORP_USER_MATCH: '29', CORP_USER_LIST: '30', USER_CORP_LIST: '31', // 员工管理
  CORP_USER_RIGHT_SCOPE: '431',
  CORP_ROLE_MANAGE: '32', CORP_ROLE_ADD: '33', CORP_ROLE_MOD: '34', CORP_ROLE_DEL: '35',
  CORP_ROLE_LIST: '36', CORP_ROLE_VIEW: '37', CORP_ROLE_MATCH: '38', // 角色管理
  CORP_REG_MANAGE: '39', CORP_REG_ADD: '40', CORP_REG_MOD: '41', CORP_PWD_CHANGE: '42',
  CORP_VIEW: '43', CORP_MATCH: '44', // 企业注册
  JOIN_CORP_MANAGE: '47', JOIN_CORP_APPLY: '48', JOIN_CORP_AUDIT: '49', // 加入企业申请
  CORP_ADMIN_MANAGE: '50', CORP_ADMIN_SET: '51', // 企业管理员
  USER_ACCOUNT: '52', USER_ACCOUNT_ALL: '53', // 账户信息
  COMMON: '54', AREA: '55', INDUSTRY: '56', STAFF_SIZE: '57', USER_REG: '58', USER_DETAIL: '59',
  USER_REAL: '60', USER_ADDRESS: '61', USER_FACE: '62', UPLOAD_LOCATION: '63', MESSAGE_CENTER: '64',
  MESSAGE_UNREAD: '65', USER_DEVICE: '66', // 通用
  OAUTH_CLIENT: '323', // 第三方应用
};

// 工单系统
export const ANYFIX_RIGHT = {
  SYS_ANYFIX: '67',
  SETTING: '68', // 系统设置
  CUSTOM_FILED: '69', CUSTOM_FILED_ADD: '70', CUSTOM_FILED_MOD: '71', CUSTOM_FILED_DEL: '72',
  CUSTOM_FILED_LIST: '73', // 自定义字段
  WORK_CONFIG: '75', // 工单配置
  WORK_TYPE: '76', WORK_TYPE_ADD: '77', WORK_TYPE_MOD: '78', WORK_TYPE_DEL: '79', WORK_TYPE_LIST: '80', // 工单类型
  REMOTE_WAY: '81', REMOTE_WAY_ADD: '82', REMOTE_WAY_MOD: '83', REMOTE_WAY_DEL: '84', REMOTE_WAY_LIST: '85', // 远程处理方式
  SERVICE_ITEM: '86', SERVICE_ITEM_ADD: '87', SERVICE_ITEM_MOD: '88', SERVICE_ITEM_DEL: '89',
  SERVICE_ITEM_LIST: '90', // 服务项目
  FAULT_TYPE: '91', FAULT_TYPE_ADD: '92', FAULT_TYPE_MOD: '93', FAULT_TYPE_DEL: '94', FAULT_TYPE_LIST: '95', // 故障现象
  SERVICE_EVALUATE: '96', SERVICE_EVALUATE_ADD: '97', SERVICE_EVALUATE_MOD: '98', SERVICE_EVALUATE_DEL: '99',
  SERVICE_EVALUATE_LIST: '100', // 服务评价指标
  WORK_ASSORT_FEE: '101', WORK_ASSORT_FEE_ADD: '102', WORK_ASSORT_FEE_MOD: '103', WORK_ASSORT_FEE_DEL: '104',
  WORK_ASSORT_FEE_VIEW: '417', // 工单分类费用规则
  SERVICE_ITEM_FEE_RULE: '105', SERVICE_ITEM_FEE_RULE_ADD: '106', SERVICE_ITEM_FEE_RULE_MOD: '107',
  WORK_IMPLEMENT_FEE: '412', WORK_IMPLEMENT_FEE_ADD: '413', WORK_IMPLEMENT_FEE_MOD: '414', WORK_IMPLEMENT_FEE_VIEW: '415', // 实施发生费用
  SERVICE_ITEM_FEE_RULE_DEL: '108',// 服务项目费用规则
  CUSTOM_REASON: '109', CUSTOM_REASON_ADD: '110', CUSTOM_REASON_MOD: '111', CUSTOM_REASON_DEL: '112',
  DATA_CONFIG: '379', DATA_CONFIG_ADD: '380',
  CUSTOM_REASON_LIST: '113', // 客户原因
  SERVICE_REASON: '114', SERVICE_REASON_ADD: '115', SERVICE_REASON_MOD: '116', SERVICE_REASON_DEL: '117',
  SERVICE_REASON_LIST: '118', SERVICE_TYPE_REASON_LIST: '119', // 服务商原因
  AUTO_CONFIG: '120', //  自动化设置
  DISPATCH_SERVICE_CORP: '121', DISPATCH_SERVICE_CORP_ADD: '122', DISPATCH_SERVICE_CORP_MOD: '123',
  DISPATCH_SERVICE_CORP_DEL: '124', // 分配服务商
  DISPATCH_SERVICE_BRANCH: '125', DISPATCH_SERVICE_BRANCH_ADD: '126', DISPATCH_SERVICE_BRANCH_MOD: '127',
  DISPATCH_SERVICE_BRANCH_DEL: '128', // 分配服务网点
  ASSIGN_MODE: '129', ASSIGN_MODE_ADD: '130', ASSIGN_MODE_MOD: '131', ASSIGN_MODE_DEL: '132', // 派单模式
  CORP_MANAGE: '133', // 企业管理
  CUSTOM_ARCHIVE: '134', CUSTOM_ARCHIVE_ADD: '135', CUSTOM_ARCHIVE_MOD: '136', CUSTOM_ARCHIVE_DEL: '137',
  CUSTOM_ARCHIVE_DETAIL: '138', CUSTOM_WORK_LIST: '139',
  CUSTOM_ARCHIVE_LIST: '140', CUSTOM_ARCHIVE_DEMANDER_LIST: '141', // 客户档案
  SERVICE_ARCHIVE: '142', SERVICE_ARCHIVE_ADD: '143', SERVICE_ARCHIVE_MOD: '144', SERVICE_ARCHIVE_DEL: '145',
  SERVICE_ARCHIVE_LIST: '146', SERVICE_ARCHIVE_DEMANDER_LIST: '147', // 服务商档案
  DEMANDER_ARCHIVE: '295', DEMANDER_ARCHIVE_ADD: '296', DEMANDER_ARCHIVE_DEL: '297', DEMANDER_ARCHIVE_MOD: '365', // 委托商档案
  DEMANDER_DETAIL: '401', // 委托商档案详情
  SERVICE_BRANCH: '148', SERVICE_BRANCH_ADD: '149', SERVICE_BRANCH_MOD: '150', SERVICE_BRANCH_DEL: '151',
  SERVICE_BRANCH_VIEW: '152', SERVICE_BRANCH_LIST: '153', SERVICE_BRANCH_MATCH: '154', // 服务网点
  SERVICE_BRANCH_USER: '155', SERVICE_BRANCH_USER_ADD: '156', SERVICE_BRANCH_USER_DEL: '157',
  SERVICE_BRANCH_USER_LIST: '158', SERVICE_BRANCH_USER_MATCH: '159', // 服务网点人员
  DEVICE_BRANCH: '160', DEVICE_BRANCH_ADD: '161', DEVICE_BRANCH_MOD: '162', DEVICE_BRANCH_DEL: '163',
  DEVICE_BRANCH_VIEW: '164', DEVICE_BRANCH_LIST: '165', DEVICE_BRANCH_MATCH: '166', // 设备网点
  DEVICE_BRANCH_USER: '167', DEVICE_BRANCH_USER_ADD: '168', DEVICE_BRANCH_USER_DEL: '169', // 设备网点人员
  USER_SKILL: '170', USER_SKILL_ADD: '171', USER_SKILL_MOD: '172', USER_SKILL_DEL: '173', // 人员技能
  //  工单管理
  WORK_MANAGE: '174', WORK_TODO: '176', WORK_HISTORY: '177', WORK_DETAIL: '178', WORK_EXPORT: '319', WORK_PDF: '398',
  WORK_ALL_LIST: '179', WORK_CURRENT_BRANCH_LIST: '180', WORK_STAT: '181', WORK_DEAL: '182',
  WORK_ATTENTION: '378', // 工单关注
  WORK_SUPPORT: '351', WORK_SUPPORT_RECORD_ADD: '352', WORK_SUPPORT_CLOSE: '353', WORK_SUPPORT_ADD: '402', // 技术支持
  WORK_ADD: '183', WORK_MOD: '313', WORK_HANDLE: '184', WORK_DISPATCH: '185', WORK_CUSTOM_RECALL: '186',
  WORK_SERVICE_RETURN: '187', WORK_TURN_HANDLE: '188', WORK_ASSIGN: '189', WORK_ASSIGN_ALL: '308', WORK_CLAIM: '190',
  WORK_ASSIGN_REFUSE: '191', WORK_ASSIGN_RETURN: '192', RETURN_ASSIGN_SERVICE: '445',WORK_ASSIGN_RECALL: '193', WORK_BOOKING_CHANGE: '194',
  WORK_SIGN: '195', WORK_REMOTE_FINISH: '196', WORK_LOCAL_FINISH: '197', WORK_EVALUATE: '198',
  WORK_WARE_USED: '200', WORK_WARE_USED_ADD: '201', WORK_WARE_USED_MOD: '202', WORK_WARE_USED_DEL: '203', // 工单使用部件
  WORK_WARE_RECYCLE: '204', WORK_WARE_RECYCLE_ADD: '205', WORK_WARE_RECYCLE_MOD: '206', WORK_WARE_RECYCLE_DEL: '207', // 工单使用部件
  WORK_POST: '208', WORK_POST_ADD: '209', WORK_POST_MOD: '210', WORK_POST_DEL: '211', // 工单换下备件邮寄单
  WORK_CHAT_DEL: '322', // 沟通记录
  WORK_FEE_VERIFY_LIST: '421', WORK_FEE_VERIFY_ADD: '422', WORK_FEE_VERIFY_MOD: '423', WORK_FEE_VERIFY_DEL: '415',
  WORK_FEE_VERIFY: '416', WORK_FEE_VERIFY_CONFIRM: '417', WORK_FEE_VERIFY_MANAGER: '446', // 对账单
  WORK_REVIEW: '337', // 客户回访记录
  WORK_REVIEW_ADD: '338', // 添加客户回访
  WORK_REVIEW_DELETE: '348', // 删除客户回访
  GOODS_POST: '359', GOODS_POST_ADD: '360', GOODS_POST_EDIT: '361', GOODS_POST_DEL: '362',
  GOODS_POST_VIEW: '363', GOODS_POST_SIGN: '364', GOODS_POST_EXPORT: '376', // 物品寄送
  WORK_FOLLOW: '405', WORK_FOLLOW_ADD: '406',
  // 工单预警设置
  WORK_REMIND_LIST: '382', WORK_REMIND_ADD: '383', WORK_REMIND_MOD: '384', WORK_REMIND_DEL: '385',
  // 结算管理
  SETTLE_MANAGE: '212', SETTLE_DEMANDER: '213', SETTLE_DEMANDER_ADD: '214', SETTLE_DEMANDER_MANAGER: '447',
  SETTLE_DEMANDER_MOD: '216', SETTLE_DEMANDER_DEL: '217', SETTLE_DEMANDER_CHECK: '218', // 委托商结算
  SETTLE_DEMANDER_FEE_INVOICE: '418', // 开票
  SETTLE_DEMANDER_FEE_PAY: '419', // 付款
  SETTLE_DEMANDER_FEE_RECEIPT: '420', // 收款
  SETTLE_CUSTOM: '219', SETTLE_CUSTOM_ADD: '220', SETTLE_CUSTOM_MOD: '221', SETTLE_CUSTOM_DEL: '222',
  SETTLE_CUSTOM_CHECK: '223', // 客户结算
  SETTLE_STAFF: '224', SETTLE_STAFF_CHECK: '226',
  SETTLE_STAFF_RECORD: '227', SETTLE_STAFF_RECORD_ADD: '228', SETTLE_STAFF_RECORD_MOD: '229',
  SETTLE_STAFF_RECORD_DEL: '230',
  FINISH_SERVICE_CHECK: '316', FINISH_MANAGER_CHECK: '442',  // 服务审核
  FEE_SERVICE_CHECK: '427', FEE_MANAGER_CHECK: '443', // 费用审核
  WORK_FINISH_CONFIRM: '231', // 服务确认
  WORK_FEE_CONFIRM: '428', // 费用确认

  WORK_FEE: '234', WORK_FEE_MOD: '237', // 工单费用
  // 工单预警列表
  WORK_REMIND_QUERY: '397',
  WORK_ATMCASE_QUERY: '310'// 金融工单查询
};

// 设备系统
export const DEVICE_RIGHT = {
  SYS_DEVICE: '238', // 设备系统
  DEVICE_CONFIG: '239', // 设备配置
  DEVICE_BRAND: '240', DEVICE_BRAND_ADD: '241', DEVICE_BRAND_MOD: '242', DEVICE_BRAND_DEL: '243',
  DEVICE_BRAND_VIEW: '244', DEVICE_BRAND_LIST: '245', DEVICE_BRAND_MATCH: '246', // 设备品牌
  DEVICE_LARGE_CLASS: '247', DEVICE_LARGE_CLASS_ADD: '248', DEVICE_LARGE_CLASS_MOD: '249',
  DEVICE_LARGE_CLASS_DEL: '250', DEVICE_LARGE_CLASS_VIEW: '251', DEVICE_LARGE_CLASS_LIST: '252',
  DEVICE_LARGE_CLASS_MATCH: '253', // 设备大类
  DEVICE_SMALL_CLASS: '254', DEVICE_SMALL_CLASS_ADD: '255', DEVICE_SMALL_CLASS_MOD: '256',
  DEVICE_SMALL_CLASS_DEL: '257', DEVICE_SMALL_CLASS_VIEW: '258', DEVICE_SMALL_CLASS_LIST: '259',
  DEVICE_SMALL_CLASS_MATCH: '260', //  设备类型
  DEVICE_CLASS_LIST: '261', // 设备分类列表
  DEVICE_SPECIFICATION: '262', // 设备规格
  DEVICE_MODEL: '263', DEVICE_MODEL_ADD: '264', DEVICE_MODEL_MOD: '265', DEVICE_MODEL_DEL: '266',
  DEVICE_MODEL_VIEW: '267', DEVICE_MODEL_LIST: '268', DEVICE_MODEL_MATCH: '269', // 设备型号
  DEVICE_INFO: '270', DEVICE_INFO_ADD: '271', DEVICE_INFO_MOD: '272', DEVICE_INFO_DEL: '273',
  DEVICE_INFO_VIEW: '274', DEVICE_INFO_LOCATE_MOD: '275', DEVICE_INFO_LOCATE_DEL: '276',
  DEVICE_INFO_SERVICE_MOD: '277', DEVICE_INFO_SERVICE_DEL: '278', DEVICE_INFO_EXPORT: '350' // 设备档案
};
// 备件系统
export const WMS_RIGHT = {
  SYS_WMS: '279'
};

// 数据分析平台
export const DIP_RIGHT = {
  SYS_DIP: '100000',
  WORK_TODO: '110001',
  INFORMATION_PLATFORM: '110002',
  WORK_CITY_CHART: '110003',
  WORK_NUMBER_CHART: '110004',
  WORK_STATUS_CHART: '110005',
  WORK_SERVICE_CHART: '110006',
  WORK_ENTRUST_CHART: '110007',
  WORK_TYPE_CHART: '110008',
  DEVICE_TYPE_PIE: '110009',
  DEMANDER_TREND_CHART: '110010'
};

// 支付系统
export const PAY_RIGHT = {
  SYS_PAY: '70000',
  PAY_ONLINE: '70001',
  PAY_CORP_ACCOUNT_VIEW: '70002',
  PAY_CORP_APPLY_VIEW: '70003',
};
