spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.34.12.145:3306/usp_msg?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: cloud.Zijin
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      logAbandoned: true
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      validationQueryTimeout: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        allow: 127.0.0.1
        reset-enable: false
        login-username: admin
        login-password: admin
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      #重试次数
      retries: 3
      #缓冲区大小，默认16KB
      batch-size: 16384
      #缓冲的存储器的总量，默认32MB
      buffer-memory: 33554432
      #序列化器接口的键
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #序列化器接口的值
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      #用于标识此使用者所属的使用者组的唯一字符串
      group-id: msg
      #默认采用手动提交的机制
      enable-auto-commit: false
      #偏移量 latest：当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
      auto-offset-reset: latest
      #序列化器接口的键
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #序列化器接口的值
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      template:
        default-topic: sms-topic
      processing:
        guarantee: exact_once
      listener:
        ack-mode: false

websocket:
  # 多实例确保值不相同
  instance-id: ${spring.cloud.client.ip-address}

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.zjft.usp.msg.model
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

msg:
  sms-type_verify: SMS_182547246
  #访问ID
  access-key-id: LTAI4FdGgY4rD8cu2fMjuPLp
  #授权秘钥
  access-key-secret: VGwSBUXnNww7HFTpiuKyaQtJ5M0eH1
  #地区
  region-id: cn-hangzhou
  #域名
  domain: dysmsapi.aliyuncs.com
  #版本
  version: 2017-05-25

logging:
  level:
    com.zjft.usp: debug
    com.alibaba.nacos.client.naming: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

jgpush:
  # 环境可选值: dev、test、prod
  environment-tag: test
  app-key: e999de664d538386114174a4
  #访问ID
  master-secret: ed22e37b113badccf7ad3527
