spring:
  datasource:
    url: jdbc:mysql://10.34.12.145:3306/usp_file?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: cloud.Zijin
  servlet:
    multipart:
      max-file-size: 300MB #限制文件上传的大小
      max-request-size: 500MB
server:
  tomcat:
    max-http-post-size: -1

# 分布式文件系统FDFS配置
fdfs:
  so-timeout: 1501 #上传的超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 10.34.12.97:22122

chenille:
  upload:
    groupName: group1   #fastdfs组名
    uploadPathName: /upload/file/ #上传存储本地文件的位置
    baseUrl: 10.34.12.97/
    allowTypes:   #允许上传的文件类型
      - image/jpeg
      - image/png

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.zjft.usp.file.model
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 3000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1

feign:
  sentinel:
    enabled: true

logging:
  level:
    com.zjft.usp: debug
    com.alibaba.nacos.client.naming: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
