spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100

  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.34.12.145:3306/usp_wms?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: cloud.Zijin
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      logAbandoned: true
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      validationQueryTimeout: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        allow: 127.0.0.1
        reset-enable: false
        login-username: admin
        login-password: admin

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  typeAliasesPackage: com.zjft.usp.wms.**.model
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#单Redis节点模式
redisson:
  model: SINGLE
  attemptTimeout: 10000 #单位 毫秒
  lockWatchdogTimeout: 30000 #单位 毫秒
  singleServerConfig:
    address: 127.0.0.1:6379

logging:
  level:
    com.zjft.usp: debug
    com.alibaba.nacos.client.naming: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS